In [128]:
import json
import numpy as np

with open("assosiative_mean.json", "r") as f:
    over_35_dict = json.load(f)

with open("billedlige_mean.json", "r") as f:
    under_35_dict = json.load(f)


In [129]:
print(len(over_35_dict))
print(len(under_35_dict))

127
127


In [130]:
print(over_35_dict)

{'0': 0.8181818181818182, '1': 0.5454545454545454, '2': 0.2727272727272727, '3': 0.7272727272727273, '4': 0.45454545454545453, '5': 0.36363636363636365, '6': 0.45454545454545453, '7': 0.5454545454545454, '8': 0.5454545454545454, '9': 0.2727272727272727, '10': 0.5454545454545454, '11': 0.36363636363636365, '12': 0.6363636363636364, '13': 0.6363636363636364, '14': 0.5454545454545454, '15': 0.7272727272727273, '16': 0.5454545454545454, '17': 0.5454545454545454, '18': 0.5454545454545454, '19': 0.45454545454545453, '20': 0.6363636363636364, '21': 0.5454545454545454, '22': 0.2727272727272727, '23': 0.45454545454545453, '24': 0.45454545454545453, '25': 0.5454545454545454, '26': 0.5454545454545454, '27': 0.45454545454545453, '28': 0.36363636363636365, '29': 0.5454545454545454, '30': 0.45454545454545453, '31': 0.6363636363636364, '32': 0.6363636363636364, '33': 0.8181818181818182, '34': 0.45454545454545453, '35': 0.2727272727272727, '36': 0.45454545454545453, '37': 0.2727272727272727, '38': 0.5

In [131]:
# Kalkulere varianse

import statistics

mean_under_35 = statistics.mean(under_35_dict.values())
variance_under35 = sum((x - mean_under_35) ** 2 for x in under_35_dict.values()) / len(under_35_dict)

mean_over_35 = statistics.mean(over_35_dict.values())
variance_over35 = sum((x - mean_over_35) ** 2 for x in over_35_dict.values()) / len(over_35_dict)

print(variance_under35)
print(variance_over35)

0.02387999837728068
0.02237025961655229


In [132]:
from scipy.stats import levene

# Convert the dictionary values to NumPy arrays
under_35_array = np.array(list(under_35_dict.values()))
over_35_array = np.array(list(over_35_dict.values()))

# Assume you have two datasets, under_35 and over_35

# Perform Levene's test
stat, p = levene(under_35_array, over_35_array)

# Print the results
print("Levene's test statistic:", stat)
print("p-value:", p)

Levene's test statistic: 1.0854403875596126
p-value: 0.29848215970295194


In [133]:
from scipy.stats import shapiro

# Utfør Shapiro-Wilk-testen
stat, p_value = shapiro(under_35_array)

# Skriv ut resultatene
print("Teststatistikk:", stat)
print("P-verdi:", p_value)

# Tolking av resultatene
alpha = 0.05  # Signifikansnivå
if p_value > alpha:
    print("Datasettet følger normalfordelingen (kan ikke avvise H0)")
else:
    print("Datasettet avviker fra normalfordelingen (avviser H0)")

Teststatistikk: 0.9370209574699402
P-verdi: 1.613538188394159e-05
Datasettet avviker fra normalfordelingen (avviser H0)


In [134]:
from scipy.stats import shapiro

# Utfør Shapiro-Wilk-testen
stat, p_value = shapiro(over_35_array)

# Skriv ut resultatene
print("Teststatistikk:", stat)
print("P-verdi:", p_value)

# Tolking av resultatene
alpha = 0.05  # Signifikansnivå
if p_value > alpha:
    print("Datasettet følger normalfordelingen (kan ikke avvise H0)")
else:
    print("Datasettet avviker fra normalfordelingen (avviser H0)")

Teststatistikk: 0.961550235748291
P-verdi: 0.0011521079577505589
Datasettet avviker fra normalfordelingen (avviser H0)


In [126]:
print(over_35_array)
print(under_35_array)
over_35_array_random = np.random.choice(over_35_array,size=9)
print(over_35_array_random)


[94.49 34.65 40.94 40.94 52.76 66.93 61.42 31.5  25.98 63.78 54.33]
[42.52 92.91 66.93 86.61 69.29 84.25 96.06 93.7  14.96]
[63.78 61.42 52.76 63.78 66.93 25.98 66.93 63.78 40.94]


In [136]:
import numpy as np
from scipy import stats
#scipy.stats.wilcoxon(x, y=None, zero_method='wilcox', correction=False, alternative='two-sided', method='auto', *, axis=0, nan_policy='propagate', keepdims=False)
# Generate two sets of sample data
group1 = under_35_array
group2 = over_35_array

# Perform Wilcoxon Rank Sum test
statistic, p_value = stats.wilcoxon(group1, group2)

# Print the test statistic and p-value
print("Test Statistic:", statistic)
print("P-value:", p_value)

Test Statistic: 605.5
P-value: 1.358843645015168e-16


In [137]:
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel

# Perform the t-test assuming equal variances
t_stat, p_value = ttest_rel(list(under_35_dict.values()), list(over_35_dict.values()))

# Print the results
print("t-statistic:", t_stat)
print("p-value:", p_value)
# Interpret the results
if t_stat < 0:
    print("The group under 35 has a lower mean.")
elif t_stat > 0:
    print("The group over 35 has a lower mean.")
else:
    print("The means of the two groups are equal.")

t-statistic: 11.656026006802861
p-value: 9.439885287190302e-22
The group over 35 has a lower mean.


ValueError: unequal length arrays

In [138]:
import numpy as np


mean_diff = np.mean(over_35_array) - np.mean(under_35_array)
pooled_std = np.sqrt((np.var(group1) + np.var(group2)) / 2)
cohen_d = mean_diff / pooled_std

print("Cohen's d:", cohen_d)

Cohen's d: -1.335272230879337
